Task3 1
js-tasks-ru/htmlcss-20210610_ivan-saltykov pull request #3
Opened 2021-06-15 12:20 UTC by dfyz85

Button element

2021-06-15 12:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-15 19:58 UTC, GSemikozov requested changes

2021-06-15 19:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
сразу убираем фиксированную ширину, вместо этого - display: inline-block и пусть ширина определяется внутренним содержимым

2021-06-15 19:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-top: 15px;
и соответственно надо задать еще паддинги слева и ссправа)

2021-06-15 19:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
здесь и ниже - стили которые уже. ранее описаны в самом блоке дублировать не надо

2021-06-15 19:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: #2342C0;
этот оттенок лучше сразу добавить в переменные

2021-06-15 19:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
то же самое что и выше

2021-06-15 19:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
при этом на кнопку все равно можно будет нажать.. поэтому советую тут (да и вообще для disabled элементов) использовать pointer-events: none

2021-06-15 19:58 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: #5028C6;
оттенок выносим в переменные

2021-06-16 10:15 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    width: 189px;
Исправил.

2021-06-16 10:15 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    padding-top: 15px;
Добавил.

2021-06-16 10:15 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    width: 189px;
Удалил.

2021-06-16 10:16 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    background-color: #2342C0;
Добавленно в переменные.

2021-06-16 10:16 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    width: 189px;
Принято

2021-06-16 10:16 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
Добавил

2021-06-16 10:17 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    background-color: #5028C6;
Добавленно в переменные.

2021-06-16 17:22 UTC, GSemikozov requested changes

2021-06-16 17:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary{
еще один важный момент - отмечу одним комментом.
у .button_primary, .button_secondary и .button_alternate очень много повторяющегося кода (стили для шрифтов, внутренние отступы и пр.). Чтобы этого избежать - нужно описать эти общие для всех типов кнопок стили в блоке .button. А вот то, что специфично для каждого отдельного типа кнопки - останется под модификатором (в этом, собственно, и суть модификатора).

кроме того, в стейтах тоже часто дублируется или описывается код, который должен быть определен на уровне блока (.button), например border-radius, cursor, border: none и пр. Просьба проверить и поправить эту часть.

2021-06-17 01:29 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +.button_primary{
Оптимизировал.

2021-06-17 08:00 UTC, GSemikozov requested changes

2021-06-17 08:00 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
это тоже надо отовсюду убрать и указать в .button - кнопка всегда по умолчанию имеет такой курсов, кроме статуса disabled, где его можно переопределить (а точнее, даже и не нано, если использовать pointer-events: none - по умолчанию будет cursor: default)

2021-06-17 08:00 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
если указан pointer-events: none (кстати, в конце надо поставить `;`) то курсор отдельно задавать не надо

2021-06-17 08:39 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
Убрал.

2021-06-17 08:41 UTC, dfyz85 commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
Согласен убрал и добавил.

2021-06-17 09:18 UTC, GSemikozov approved these changes

2021-06-17 09:18 UTC, merged