Task3 2
js-tasks-ru/htmlcss-20210610_ivan-saltykov pull request #4
Opened 2021-06-15 12:21 UTC by dfyz85

Accordion element

2021-06-15 12:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-15 20:02 UTC, GSemikozov requested changes

2021-06-15 20:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion  * {
низзя в БЭМ использовать универсальные селекторы ;)

2021-06-15 20:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    transform: rotate(180deg)translate(0, +10%);
пробел бы еще между значениями

2021-06-15 20:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.acordion__summary_flex{
тут надо бы следовать принципу единственной ответственности и обратить внимание на то, что название модификатора говорит нам о том, что элемент станет флексом (и тогда в дополнение добавить justify-content: space-between; это ок). Но вот то что мы изменим курсор - это неясно из названия класса)
вообще, я думаю что в таком модификаторе нет смысла, эти стили можно сразу в самом элементе определить

2021-06-16 00:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-16 02:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-16 10:01 UTC, dfyz85 commented on 03-lection1/02-accordion/accordion.css
> +.accordion  * {
Согласен убрал.

2021-06-16 10:01 UTC, dfyz85 commented on 03-lection1/02-accordion/accordion.css
> +    transform: rotate(180deg)translate(0, +10%);
добавил

2021-06-16 10:12 UTC, dfyz85 commented on 03-lection1/02-accordion/accordion.css
> +.acordion__summary_flex{
Исправил частично, причина в следующем 

1. Без `display: none;` не работает в `Google Chrome`, добовляется `::marker`

2. `.acordion__summary_flex` выступает как wraper внутри `<summary>`, без него `<summary>` не работает с  `flexbox`

На другое решения нехватает опыта:)

2021-06-16 17:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.acordion__summary_flex{
нет-нет, я имел в виду, что стили которые определены под классом .acordion__summary_flex можно перенести в сам блок .acordion__summary, а модификатор удалить

2021-06-17 01:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-17 01:35 UTC, dfyz85 commented on 03-lection1/02-accordion/accordion.css
> +.acordion__summary_flex{
я понял, но без такой конструкции если `<summary>  display: flex` стрелка некоректно отображается в `Safari`


<img width="1129" alt="Снимок экрана 2021-06-17 в 10 27 34" src="https://user-images.githubusercontent.com/304321/122316697-4adc7b80-cf57-11eb-9ca9-02def04b11e2.png">

2021-06-17 08:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.acordion__summary_flex{
стрелку нужно позиционировать абсолютно, но мы эту тему еще не изучали, поэтому рекомендуется кастомную стрелку пока не добавлять

2021-06-17 08:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-17 09:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-17 09:05 UTC, dfyz85 commented on 03-lection1/02-accordion/accordion.css
> +.acordion__summary_flex{
Исправил, спасибо за совет.

2021-06-17 09:19 UTC, GSemikozov approved these changes

2021-06-17 09:19 UTC, merged